/**
 * Form Templates for Task Intake
 * Public/internal forms to create tasks with conditional fields
 */

const FORM_TEMPLATES = {
  // Bug Report Form
  bugReport: {
    id: 'bugReport',
    name: 'Bug Report',
    description: 'Report a bug or issue',
    type: 'public',
    fields: [
      {
        id: 'title',
        name: 'Bug Title',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the bug',
        order: 1,
      },
      {
        id: 'description',
        name: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the issue',
        order: 2,
      },
      {
        id: 'severity',
        name: 'Severity',
        type: 'select',
        required: true,
        options: [
          { value: 'critical', label: 'Critical - System down' },
          { value: 'high', label: 'High - Major functionality broken' },
          { value: 'medium', label: 'Medium - Feature not working as expected' },
          { value: 'low', label: 'Low - Minor issue' },
        ],
        order: 3,
      },
      {
        id: 'stepsToReproduce',
        name: 'Steps to Reproduce',
        type: 'textarea',
        required: true,
        placeholder: '1. Step one\n2. Step two\n3. Step three',
        order: 4,
      },
      {
        id: 'expectedBehavior',
        name: 'Expected Behavior',
        type: 'textarea',
        required: true,
        placeholder: 'What should happen',
        order: 5,
      },
      {
        id: 'actualBehavior',
        name: 'Actual Behavior',
        type: 'textarea',
        required: true,
        placeholder: 'What actually happens',
        order: 6,
      },
      {
        id: 'environment',
        name: 'Environment',
        type: 'select',
        required: true,
        options: [
          { value: 'production', label: 'Production' },
          { value: 'staging', label: 'Staging' },
          { value: 'development', label: 'Development' },
          { value: 'local', label: 'Local' },
        ],
        order: 7,
      },
      {
        id: 'attachments',
        name: 'Attachments (Screenshots/Logs)',
        type: 'file',
        required: false,
        multiple: true,
        order: 8,
      },
    ],
    autoAssign: {
      project: 'bug-tracking',
      queue: 'bug-queue',
      priority: 'high',
      taskType: 'bug',
    },
    approvalWorkflow: 'quickApproval',
  },

  // Feature Request Form
  featureRequest: {
    id: 'featureRequest',
    name: 'Feature Request',
    description: 'Request a new feature or enhancement',
    type: 'public',
    fields: [
      {
        id: 'title',
        name: 'Feature Title',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the feature',
        order: 1,
      },
      {
        id: 'description',
        name: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the feature',
        order: 2,
      },
      {
        id: 'useCase',
        name: 'Use Case',
        type: 'textarea',
        required: true,
        placeholder: 'How would this feature be used?',
        order: 3,
      },
      {
        id: 'priority',
        name: 'Priority',
        type: 'select',
        required: true,
        options: [
          { value: 'critical', label: 'Critical - Blocks work' },
          { value: 'high', label: 'High - Important' },
          { value: 'medium', label: 'Medium - Nice to have' },
          { value: 'low', label: 'Low - Future consideration' },
        ],
        order: 4,
      },
      {
        id: 'estimatedCost',
        name: 'Estimated Cost ($)',
        type: 'number',
        required: false,
        placeholder: '0',
        order: 5,
      },
      {
        id: 'requiresApproval',
        name: 'Requires Approval',
        type: 'checkbox',
        required: false,
        order: 6,
        condition: {
          field: 'estimatedCost',
          operator: 'greaterThan',
          value: 10000,
        },
      },
      {
        id: 'attachments',
        name: 'Attachments (Mockups/Docs)',
        type: 'file',
        required: false,
        multiple: true,
        order: 7,
      },
    ],
    autoAssign: {
      project: 'product-backlog',
      queue: 'feature-queue',
      priority: 'medium',
      taskType: 'feature',
    },
    approvalWorkflow: 'costBasedApproval',
  },

  // IT Ticket Form
  itTicket: {
    id: 'itTicket',
    name: 'IT Support Ticket',
    description: 'Request IT support or report an issue',
    type: 'internal',
    fields: [
      {
        id: 'title',
        name: 'Issue Title',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the issue',
        order: 1,
      },
      {
        id: 'category',
        name: 'Category',
        type: 'select',
        required: true,
        options: [
          { value: 'hardware', label: 'Hardware' },
          { value: 'software', label: 'Software' },
          { value: 'network', label: 'Network' },
          { value: 'access', label: 'Access/Permissions' },
          { value: 'other', label: 'Other' },
        ],
        order: 2,
      },
      {
        id: 'description',
        name: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the issue',
        order: 3,
      },
      {
        id: 'severity',
        name: 'Severity',
        type: 'select',
        required: true,
        options: [
          { value: 'critical', label: 'Critical - Cannot work' },
          { value: 'high', label: 'High - Significant impact' },
          { value: 'medium', label: 'Medium - Some impact' },
          { value: 'low', label: 'Low - Minor issue' },
        ],
        order: 4,
      },
      {
        id: 'affectedUsers',
        name: 'Number of Affected Users',
        type: 'number',
        required: true,
        placeholder: '1',
        order: 5,
      },
      {
        id: 'deviceInfo',
        name: 'Device/System Info',
        type: 'textarea',
        required: false,
        placeholder: 'OS, software versions, etc.',
        order: 6,
      },
      {
        id: 'attachments',
        name: 'Attachments (Screenshots/Logs)',
        type: 'file',
        required: false,
        multiple: true,
        order: 7,
      },
    ],
    autoAssign: {
      project: 'it-support',
      queue: 'support-queue',
      priority: 'high',
      taskType: 'support',
    },
    approvalWorkflow: null,
  },

  // Change Request Form
  changeRequest: {
    id: 'changeRequest',
    name: 'Change Request',
    description: 'Request a change to production systems',
    type: 'internal',
    fields: [
      {
        id: 'title',
        name: 'Change Title',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the change',
        order: 1,
      },
      {
        id: 'description',
        name: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the change',
        order: 2,
      },
      {
        id: 'reason',
        name: 'Reason for Change',
        type: 'textarea',
        required: true,
        placeholder: 'Why is this change needed?',
        order: 3,
      },
      {
        id: 'impact',
        name: 'Impact Assessment',
        type: 'textarea',
        required: true,
        placeholder: 'What systems/users will be affected?',
        order: 4,
      },
      {
        id: 'riskLevel',
        name: 'Risk Level',
        type: 'select',
        required: true,
        options: [
          { value: 'low', label: 'Low Risk' },
          { value: 'medium', label: 'Medium Risk' },
          { value: 'high', label: 'High Risk' },
        ],
        order: 5,
      },
      {
        id: 'rollbackPlan',
        name: 'Rollback Plan',
        type: 'textarea',
        required: true,
        placeholder: 'How will we rollback if something goes wrong?',
        order: 6,
      },
      {
        id: 'scheduledDate',
        name: 'Scheduled Date',
        type: 'date',
        required: true,
        order: 7,
      },
      {
        id: 'estimatedDuration',
        name: 'Estimated Duration (minutes)',
        type: 'number',
        required: true,
        placeholder: '30',
        order: 8,
      },
      {
        id: 'attachments',
        name: 'Attachments (Plans/Docs)',
        type: 'file',
        required: false,
        multiple: true,
        order: 9,
      },
    ],
    autoAssign: {
      project: 'change-management',
      queue: 'change-queue',
      priority: 'high',
      taskType: 'change',
    },
    approvalWorkflow: 'standardApproval',
  },

  // Expense Request Form
  expenseRequest: {
    id: 'expenseRequest',
    name: 'Expense Request',
    description: 'Request approval for an expense',
    type: 'internal',
    fields: [
      {
        id: 'title',
        name: 'Expense Title',
        type: 'text',
        required: true,
        placeholder: 'What is this expense for?',
        order: 1,
      },
      {
        id: 'category',
        name: 'Category',
        type: 'select',
        required: true,
        options: [
          { value: 'travel', label: 'Travel' },
          { value: 'meals', label: 'Meals & Entertainment' },
          { value: 'equipment', label: 'Equipment' },
          { value: 'software', label: 'Software/Licenses' },
          { value: 'training', label: 'Training' },
          { value: 'other', label: 'Other' },
        ],
        order: 2,
      },
      {
        id: 'amount',
        name: 'Amount ($)',
        type: 'number',
        required: true,
        placeholder: '0.00',
        order: 3,
      },
      {
        id: 'description',
        name: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the expense',
        order: 4,
      },
      {
        id: 'businessJustification',
        name: 'Business Justification',
        type: 'textarea',
        required: true,
        placeholder: 'Why is this expense necessary?',
        order: 5,
      },
      {
        id: 'requiresApproval',
        name: 'Requires Director Approval',
        type: 'checkbox',
        required: false,
        order: 6,
        condition: {
          field: 'amount',
          operator: 'greaterThan',
          value: 5000,
        },
      },
      {
        id: 'requiresCFOApproval',
        name: 'Requires CFO Approval',
        type: 'checkbox',
        required: false,
        order: 7,
        condition: {
          field: 'amount',
          operator: 'greaterThan',
          value: 25000,
        },
      },
      {
        id: 'receipt',
        name: 'Receipt/Invoice',
        type: 'file',
        required: true,
        order: 8,
      },
    ],
    autoAssign: {
      project: 'finance',
      queue: 'expense-queue',
      priority: 'medium',
      taskType: 'expense',
    },
    approvalWorkflow: 'costBasedApproval',
  },
};

module.exports = FORM_TEMPLATES;
